name: Release

on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: clone repo
        uses: actions/checkout@v4


      - name: build
        run: |
          rm -rf dist
          yarn install
          yarn build
  
      # commit file
      - uses: stefanzweifel/git-auto-commit-action@v5

      - uses: gacts/purge-jsdelivr-cache@v1
        with:
          url: |
            https://cdn.jsdelivr.net/npm/@ngatngay/js-helper/dist/ngatngay.js
            https://cdn.jsdelivr.net/npm/@ngatngay/js-helper/dist/jquery.js
